MODEL_DETECT_FACE_XML = "models/face_detection_retail_0004/FP32/face_detection_retail_0004.xml"
MODEL_DETECT_FACE_BIN = "models/face_detection_retail_0004/FP32/face_detection_retail_0004.bin"
SHAPE_OF_TRANSPOSE = (2, 0, 1)
CONF_FACE_DETECTION_THRESHOLD = 0.5
FACE_SIZE = 112
ARCFACE_MODEL_PATH = 'models/model.tflite'
ARCFACE_MODEL_URL = 'https://www.digidow.eu/f/datasets/arcface-tensorflowlite/model.tflite'
FOLDERDATA = 'faceData'
MAXIMUM_DISTANCE = 999
FACE_VERIFY_THRESHOLD = 0.85